# NumPy Fundamentals: Manipulating Matrices
Please follow the instructions and uncomment the skeleton code as necessary.

This assignment is due in addition to the small group assignment before the next class

In [ ]:
import numpy as np

In [ ]:
# Create a 3x3x3 np.array
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
print(my_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


## Multidimensional Indexing

### Q.1 Print the value `2.0` from `my_array` using its index

In [ ]:
print(my_array[1, 0, 0])

#### Q.2 Use multidimensional slicing to print a 3x3 array that contains *all* values of `2` from `my_array`.

In [ ]:
print(my_array[1, :, :])

#### Q.3 Use multidimensional slicing to add `5` to every other element in `my_array` such that `print(new_array)` outputs

```python
[[[6. 1. 6.]
  [1. 6. 1.]
  [6. 1. 6.]]

 [[7. 2. 7.]
  [2. 7. 2.]
  [7. 2. 7.]]

 [[8. 3. 8.]
  [3. 8. 3.]
  [8. 3. 8.]]]
```

In [ ]:
# create a copy of my_array named new_array
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
new_array = my_array

# add 5 to every other element
new_array[:, ::2, ::2] += 5         # add 5 to the corner elements
new_array[:, 1, 1 ] += 5         # add 5 to the center elements
#print(new_array)


## Reshaping Matrices

#### Please refer to your notes on the `transpose`, `reshape`, and `flatten` methods to answer questions 4-6. 

#### Q.4 Create a 1D array from on `my_array`.

In [ ]:
my_1d_array = my_array.flatten()
print(my_1d_array)

#### Q.5 Create a 2D array from `my_array` that has 3 rows and 9 columns

In [ ]:
my_2d_array = my_array.reshape(3, 9)
print(my_2d_array)

#### Q.6 Create a new 3D array from `my_array` so that each 3x3 sub-array has at least one row with the values `[1, 2, 3]`.

In [ ]:
my_array[:, 0, :] = [1, 2, 3]
transposed_array = my_array
print(transposed_array)